### ISSUE TITLE
Planned WHMCS features (TODO list)

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/openpanel-whmcs-module#1]
- [x] separate function for reusing the jwt
- [x] another to revalidate and issue new if needed
- [x] prettier error and success messages
- [ ]  extended Icons for client area: e-mail, database, domains, file manager..
- [x]  ~installer~

**Comment by stefanpejcic** [comment]
Installer Is Done in readme

**Comment by caesarmind** [comment]
Isn't it better to not cache jwt in terms of security? What's the problem with getting new jwt everytime there is request? how many request in a minute should be there to create load? It probably will be less than 100 request in a minute at the most in practice.

**Comment by stefanpejcic** [comment]
Without storing the token, we would need to send user and pass for each request, that is how the module works now.

For security it is better to just reuse the token. It's stored only in the memory on the whmcs server

**Comment by stefanpejcic** [comment]
from whmcs docs, there is no existing caching storage that can be used like transients, so only way to store the token would be trough the database or files. For now we'll keep the current logic and generate a new token on each request.

Only thing left on the todo is:
> extended Icons for client area: e-mail, database, domains, file manager..
